"""add unique constraint to attendance

Revision ID: 678f8d9bdbd5
Revises: 20260312_01
Create Date: 2026-04-18 18:22:04.872820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '678f8d9bdbd5'
down_revision: Union[str, Sequence[str], None] = '20260312_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Remove duplicates, keeping the one with smallest id
    op.execute("""
        DELETE FROM attendance
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM attendance
            GROUP BY date, class_id, absent_name, status
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance', 'attendance', ['date', 'class_id', 'absent_name', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance', 'attendance', type_='unique')
    # ### end Alembic commands ###
